### ISSUE TITLE
Getting Update notification in latest update

### ISSUE THREAD

**Issue by nbycoder** [maxasix/AltLinux#1]
Title is pretty self explanatory. I'm on Pop OS 22.04, and each time I receive a notification asking to update. However, I'm using the latest release.

![image](https://user-images.githubusercontent.com/90400844/192149354-3c4999f8-5f9e-4947-85f6-596bccc7ae79.png)
![image](https://user-images.githubusercontent.com/90400844/192149376-1a458445-57ad-4021-9fdd-fa61436f3cee.png)

**Comment by maxasix** [comment]
Fixed.
